REMOTE_ENV = "REMOTE"
LOCAL_ENV = "LOCAL"
DOCKER_ENV = "DOCKER"
WINDOWS_ENV = "WINDOWS"

LINAL_LABS_COUNT = 15
ANGEM_LABS_COUNT = 10

MAX_SIZE_LOG_FILE = 20*1024*1024
COUNT_LOG_FILES = 5

DB_RETRY_COUNT = 10
DB_RETRY_SLEEP_SECONDS = 2

AUTH_SECRET_KEY = "SECRET"  # TODO: add to .env
AUTH_HASH_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_DAYS = 7